services:
  tailgate:
    image: valentemath/tailgate:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INCLUDE_SABLIER: "false"
        TAILSCALE_VERSION: "${TAILSCALE_VERSION:-}"
        SABLIER_VERSION: "${SABLIER_VERSION:-}"
        PLUGINS: "github.com/caddy-dns/cloudflare"

  tailgate-sablier:
    image: valentemath/tailgate:latest-with-sablier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INCLUDE_SABLIER: "true"
        TAILSCALE_VERSION: "${TAILSCALE_VERSION:-}"
        SABLIER_VERSION: "${SABLIER_VERSION:-}"
        PLUGINS: "
          github.com/caddy-dns/cloudflare
          github.com/sablierapp/sablier-caddy-plugin
          "
        # PLUGINS: "
        #   github.com/caddy-dns/cloudflare
        #   github.com/acouvreur/sablier/plugins/caddy
        #   "
