services:
  tailnet-caddy:
    image: ghcr.io/sudosu404/tailnet-caddy:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLUGINS: "
          github.com/caddy-dns/cloudflare
          github.com/sablierapp/sablier/plugins/caddy
          "
    volumes:
      - tailscale-state:/tailscale
      - caddy-config:/etc/caddy

volumes:
  tailscale-state:
  caddy-config: