services:
  tailnet:
    image: sudosu404/tailnet-caddy:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLUGINS: "github.com/caddy-dns/cloudflare"

  tailnet-sablier:
     image: sudosu404/tailnet-caddy:latest-with-sablier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLUGINS: "
          github.com/caddy-dns/cloudflare
          github.com/sablierapp/sablier/plugins/caddy
          "
